### ISSUE TITLE
Problem subscribing to image and camera_info

### ISSUE THREAD

**Issue by rommelalonzo** [ros-perception/depthimage_to_laserscan#10]
Problem subscribing to image and camera_info
## I'm trying to launch the depthimage-to-laserscan ROS node using a launch file. 

```
<node pkg="depthimage_to_laserscan" type="depthimage_to_laserscan" name="depthimage_to_laserscan">
  <remap from="scan" to="laserbeam"/>
  <param name="camera_info" value="/cam1/camera_info"/>
  <param name="image" value="/cam1/line_finder"/>
</node>
```

---

I pumped the original image through a preprocessing program that outputs a simple bitmap image. 
![Preprocessing Picture](https://cloud.githubusercontent.com/assets/2065767/3166413/7f74ff8a-eb60-11e3-9c6c-578e85b50749.jpg)

However, when I run the launch file, the node successfully launches but doesn't subscribe to anything. When I look up information on the node and what it connects to using rosnode info, this is the output:

---

Node [/depthimage_to_laserscan]
Publications: 
- /depthimage_to_laserscan/parameter_updates [dynamic_reconfigure/Config]
- /rosout [rosgraph_msgs/Log]
- /depthimage_to_laserscan/parameter_descriptions [dynamic_reconfigure/ConfigDescription]
- /laserbeam [sensor_msgs/LaserScan]

Subscriptions: None

Services: 
- /depthimage_to_laserscan/get_loggers
- /depthimage_to_laserscan/set_logger_level
- /depthimage_to_laserscan/set_parameters

contacting node http://romo-MacBookPro:52274/ ...
Pid: 20486
Connections:
- topic: /rosout
  - to: /rosout
  - direction: outbound
  - transport: TCPROS

---

According to the printout above, the node doesn't subscribe to anything. Any advice would greatly be appreciated. 

PS: I'm planning on combining this output with a laser scan from a hokuyo sensor. Any pointers would greatly be appreciated.

**Comment by ctanzer** [comment]
Is there already a solution for this problem?

**Comment by tfoote** [comment]
This is expected. 

This node does lazy subscriptions so that it doesn't listen to the depth image topic to save bandwidth. 

https://github.com/ros-perception/depthimage_to_laserscan/blob/indigo-devel/src/DepthImageToLaserScanROS.cpp#L46

https://github.com/ros-perception/depthimage_to_laserscan/blob/indigo-devel/src/DepthImageToLaserScanROS.cpp#L69-L84

**Comment by pallavbakshi** [comment]
@ctanzer Hey! Could you explain what you did so that it can be helpful for all of us? The [ROS depthimage to laserscan](http://wiki.ros.org/depthimage_to_laserscan) page mentions that the subscribed topics are image and camera_info but when I look at the subscribed topic then I don't see any. However, I can see some data out of /scan. What is happening here? 

Thank you for your help in advance!!

**Comment by ctanzer** [comment]
First You need to tell the node where to find the depth image you want to transform. You can do this with 

`<remap from="image" to="your/topic"/>`

in a launch-file. As it is already mentioned above.

After that I made a mistake: I didn't read the manual properly!

> depthimage_to_laserscan uses lazy subscribing and will not subscribe to image or camera_info until there is a subscriber for scan.

When I was adding the output topic (default "/scan") to rviz the node (/depthimage_to_laserscan) was subscribing to my remapped depth image. Means the node is only subscribing to the image if some other node(s) are subscribing to its own output.

But I can't explain why You are seeing data in Your "/scan" topic. Maybe You have another node running publishing a "/scan" topic too?

**Comment by pallavbakshi** [comment]
Hi @ctanzer Thank you for the explanation. There was only one /scan topic being published and that by the depthimage_to_laserscan node. I don't know why I was able to see the output of /scan topic even if nothing was subscribed to the same. However, I tried testing it with hector slam and it work perfectly. Thank you so much for your explanation. I have a question on ROS wiki regarding the same. If you would like to gain some points over there then simply copy paste the answer over there and I will accept it. However if not then I will simply update my question with your answer so that it might be helpful for someone having similar issue next time. 

http://answers.ros.org/question/253473/depthimage_to_laserscan-not-subscribing-to-depth-by-kinect-360/

Thanks
