### ISSUE TITLE
Failed to build with ROS2 Bouncy release

### ISSUE THREAD

**Issue by qiuzhong** [ros-perception/depthimage_to_laserscan#30]
Tried to build this package with the [RO2 Bouncy release](https://github.com/ros2/ros2/releases) but got blocked. Here are the steps and logs:
 
```
$ source <path/to/ros2-linux>/local_setup.bash
$ mkdir -pv ~/ros2_ws/src
$ cd ~/ros2_ws/src
$ git clone https://github.com/ros-perception/depthimage_to_laserscan.git
$ git clone https://github.com/ros-perception/vision_opencv.git
$ cd ~/ros2_ws
$  colcon build --symlink-install --packages-select image_geometry depthimage_to_laserscan
Starting >>> image_geometry
Finished <<< image_geometry [4.86s]                       
Starting >>> depthimage_to_laserscan
--- stderr: depthimage_to_laserscan                         
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.


---
Failed   <<< depthimage_to_laserscan	[ Exited with code 1 ]

Summary: 1 package finished [6.76s]
  1 package failed: depthimage_to_laserscan
  1 package had stderr output: depthimage_to_laserscan
```

**Notice**, `vision_openv/image_geometry` is need as it must be built before building the `depthimage_to_laserscan` package.

**Comment by mikaelarguedas** [comment]
This fails to compile because you are using the ROS1 version of these packages.
You need to use the ros2 fork of depthimage_to_laserscan and the ros2 branch of the vision_opencv repository.
The list of repositories for the ROS 2 core can be found [here](https://github.com/ros2/ros2/blob/bouncy/ros2.repos) and the higher level packages (Linux only ATM) can be found [here](https://github.com/ros2/turtlebot2_demo/blob/bouncy/turtlebot2_demo.repos).

As we recommend to ask questions on answers.ros.org I'm going to close this ticket. If you face any more issue please ask a question on answers.ros.org and if possible comment here with the link for future readers.
HTH
