### ISSUE TITLE
potential bug in range computation

### ISSUE THREAD

**Issue by piyushk** [ros-perception/depthimage_to_laserscan#6]
https://github.com/ros-perception/depthimage_to_laserscan/blob/hydro-devel/include/depthimage_to_laserscan/DepthImageToLaserScan.h#L203

If I am not mistaken, the y component should not be a part of the range computation. It is the dimension we are doing away with. Since we take the minimum of all distances as the range value, the output is still correct for completely vertical surfaces.

If someone can confirm this, I can submit a patch.

**Comment by chadrockey** [comment]
@piyushk Yeah, I think you're right.  No ones ever noticed since it's rarely used in wide-mode.

Here's the commited fix (released in 1.0.6):
https://github.com/ros-perception/depthimage_to_laserscan/commit/0c76a0bef8fde5aad77232ccc3ac04660ee5cca1

Here's the BEFORE top-down orthographic projection:

![old](https://f.cloud.github.com/assets/230240/1451245/61873758-4292-11e3-8eae-b6d246565c1d.png)

Here's the FIXED top-down orthographic projection:

![fix](https://f.cloud.github.com/assets/230240/1451246/6c67958c-4292-11e3-8501-bafc1f67b9ef.png)

**Comment by chadrockey** [comment]
The above screenshots were generated by setting the scan height to something large (like 471 pixels) and putting tall vertical obstacles (like a column or wall) along the bottom of the depthimage.

From the top-down othographic view, we want the laserscan to wrap the outline of all obstacles in this case.  The top image clearly shows it inside of many obstacles.  The bottom image shows it outlining the laptop and column.
